базовые стилизации
htmlacademy-htmlcss/2105483-sedona-36 pull request #4
Opened 2023-03-08 13:07 UTC by shahinya27

2023-03-10 08:30 UTC, Mielilon requested changes
В целом, могу сказать, что работа неплохая. Текстовые стили заданы там, где это нужно, осталось исправить небольшие недочеты. 

Важный момент! Сейчас в разметке есть ошибки, которые не дают правильно отображаться элементам. Пропусти свой код через [сервис](https://validator.w3.org/nu/#textarea) и поправь все неточности, которые относятся к закрывающим тегам.

2023-03-10 08:30 UTC, Mielilon commented on styles/styles.css
> +  background-color: cover;
Мы не можем ставить `background-color: cover;`, так как такого свойства не существует. Как я понимаю, ты хотела сделать так, чтобы фон-картинка растягивался на весь блок. Для этого воспользуемся `background-size: cover;`

2023-03-10 08:30 UTC, Mielilon commented on index.html
>      <div class="welcome-img-wrapper">
В данном случае, поменяем `div` на `section`, так как это независимый блок-секция. Также изменим класс. Например, на `welcome-content-wrapper`. Сюда же переместим скрытый заголовок `h1`
<img width="723" alt="image" src="https://user-images.githubusercontent.com/65778664/224262053-be7660b0-c85e-4d3b-8764-46fadd41ff97.png">

2023-03-10 08:30 UTC, Mielilon commented on styles/styles.css
> + font-weight: 700;
Все установки для шрифта нужно задавать не блоку обертке, а дочерним элементам. Таким как `advantages-title`, `advantages-text` и тд. Потому что они имеют разные стили. 

Дополнительно отмечу, что подряд идет два одинаковых класса и их стили перекрывают друг-друга:
![image](https://user-images.githubusercontent.com/65778664/224262856-b53c417d-cc2b-4495-9a54-918e1b10888d.png)

2023-03-10 08:30 UTC, Mielilon commented on styles/styles.css
> +.advantages-list {
Замечание относится к разметке:
<img width="592" alt="image" src="https://user-images.githubusercontent.com/65778664/224263616-7825c45f-0eb7-4a1a-8420-dcdb1db63425.png">

2023-03-12 12:11 UTC, shahinya27 commented
переделала ошибки

2023-03-13 17:30 UTC, merged